site_name: Panini 

site_url: https://github.com/ihucos/panini
repo_url: https://github.com/ihucos/panini

nav:
  - Quickstart: index.md
  - Tutorial: tutorial.md
  - Reference:
    - Section Types: drivers.md
    - Section Type Declaration: section_type_declaration.md
    - Global Keys: global_keys.md
  - Recipes:
    - Local Environment Variables: localenvs.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

theme:
  palette:
    primary: "blue grey"
  name: material
  logo: "assets/panini.png"
  features:
    - content.code.copy
    - navigation.sections
