

jobs:
  plash:
    test:
      build:
        - from: alpine:edge
        - run: "apk add python3 py3-pip"
        - check: requirements.txt
        - run: "pip3 install --break-system-packages -r requirements.txt"
        - pin: base
      command: "python3 ./manage.py test"

    devserver:
      build:
        - from-pin: base
      command: "python3 ./manage.py devserver"

  uv:
    pycowsay:
      python: pypy@3.8
      no_project: true
      with:
        - pycowsay
      command: pycowsay hi
  
  docker:
    mysql:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: myuser
        MYSQL_PASSWORD: mypassword
      ports:
        - "3306:3306"


uv "pycowsay" {
  with=["pycowsay"]
}


docker "mysql" {
  image="mysql:latest"
  ports=["3306:3306"]
  envs {
    MYSQL_ROOT_PASSWORD=rootpassword
    MYSQL_DATABASE=mydatabase
    MYSQL_USER=myuser
    MYSQL_PASSWORD=mypassword
}
}
